### PR TITLE
add relative paths option

### PR DESCRIPTION
**Pull request by yannikmethot**

### CODE REVIEW

**Comment by yannikmethot** [comment]
@AaronAsAChimp, I did the changes you asked, let me know what you think. Thanks!

**Comment by AaronAsAChimp** [comment]
Please make sure to use tabs for indentation.

**Comment by yannikmethot** [comment]
@AaronAsAChimp, fixed.

**Comment by yannikmethot** [comment]
@AaronAsAChimp, is it possible to create the tag 1.0.2 with the changes you merged for the option.root please? Thanks!

**Comment by AaronAsAChimp** [comment]
Done

**Comment by yannikmethot** [comment]
Thanks!

**Pull request merged**
